### ISSUE TITLE
Remove .mailmap

### ISSUE THREAD

**Issue by jdfreder** [ipython/ipython_widgets#17]
@minrk is it okay if we remove this file?  What is it for?  It looks like a contributor list, have you already simplified it for the widget contributors?

**Comment by minrk** [comment]
@jdfreder it should stay on all repos. It's a deduplication map that fixes the entries in `git log` so that when people contribute commits from different emails they don't show up as multiple unique authors. If you want to find the examples that don't show up on a given repo you can, but I don't think it's worth your time. This is just a mapping, so entries that aren't in the actual logs have no effect anywhere.

The email logging is something akin to:

```python
logged_email = mailmap.get(actual_email, actual_email)
```

For an example, see the output of `git shortlog -s` with and without the mailmap file.
